/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMeuPerfilRouteImport } from './routes/_authenticated/meu-perfil'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAprovacoesRouteImport } from './routes/_authenticated/aprovacoes'
import { Route as AuthenticatedTutoresIndexRouteImport } from './routes/_authenticated/tutores.index'
import { Route as AuthenticatedTurmasIndexRouteImport } from './routes/_authenticated/turmas.index'
import { Route as AuthenticatedAlunosIndexRouteImport } from './routes/_authenticated/alunos.index'
import { Route as AuthenticatedTutoresNovoRouteImport } from './routes/_authenticated/tutores.novo'
import { Route as AuthenticatedTutoresIdRouteImport } from './routes/_authenticated/tutores.$id'
import { Route as AuthenticatedTurmasNovaRouteImport } from './routes/_authenticated/turmas.nova'
import { Route as AuthenticatedTurmasIdRouteImport } from './routes/_authenticated/turmas.$id'
import { Route as AuthenticatedAlunosNovoRouteImport } from './routes/_authenticated/alunos.novo'
import { Route as AuthenticatedAlunosIdRouteImport } from './routes/_authenticated/alunos.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeuPerfilRoute = AuthenticatedMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAprovacoesRoute = AuthenticatedAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTutoresIndexRoute =
  AuthenticatedTutoresIndexRouteImport.update({
    id: '/tutores/',
    path: '/tutores/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTurmasIndexRoute =
  AuthenticatedTurmasIndexRouteImport.update({
    id: '/turmas/',
    path: '/turmas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlunosIndexRoute =
  AuthenticatedAlunosIndexRouteImport.update({
    id: '/alunos/',
    path: '/alunos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTutoresNovoRoute =
  AuthenticatedTutoresNovoRouteImport.update({
    id: '/tutores/novo',
    path: '/tutores/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTutoresIdRoute = AuthenticatedTutoresIdRouteImport.update({
  id: '/tutores/$id',
  path: '/tutores/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTurmasNovaRoute = AuthenticatedTurmasNovaRouteImport.update({
  id: '/turmas/nova',
  path: '/turmas/nova',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTurmasIdRoute = AuthenticatedTurmasIdRouteImport.update({
  id: '/turmas/$id',
  path: '/turmas/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlunosNovoRoute = AuthenticatedAlunosNovoRouteImport.update({
  id: '/alunos/novo',
  path: '/alunos/novo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlunosIdRoute = AuthenticatedAlunosIdRouteImport.update({
  id: '/alunos/$id',
  path: '/alunos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/alunos/$id': typeof AuthenticatedAlunosIdRoute
  '/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/turmas/$id': typeof AuthenticatedTurmasIdRoute
  '/turmas/nova': typeof AuthenticatedTurmasNovaRoute
  '/tutores/$id': typeof AuthenticatedTutoresIdRoute
  '/tutores/novo': typeof AuthenticatedTutoresNovoRoute
  '/alunos/': typeof AuthenticatedAlunosIndexRoute
  '/turmas/': typeof AuthenticatedTurmasIndexRoute
  '/tutores/': typeof AuthenticatedTutoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/alunos/$id': typeof AuthenticatedAlunosIdRoute
  '/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/turmas/$id': typeof AuthenticatedTurmasIdRoute
  '/turmas/nova': typeof AuthenticatedTurmasNovaRoute
  '/tutores/$id': typeof AuthenticatedTutoresIdRoute
  '/tutores/novo': typeof AuthenticatedTutoresNovoRoute
  '/alunos': typeof AuthenticatedAlunosIndexRoute
  '/turmas': typeof AuthenticatedTurmasIndexRoute
  '/tutores': typeof AuthenticatedTutoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_authenticated/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/_authenticated/alunos/$id': typeof AuthenticatedAlunosIdRoute
  '/_authenticated/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/_authenticated/turmas/$id': typeof AuthenticatedTurmasIdRoute
  '/_authenticated/turmas/nova': typeof AuthenticatedTurmasNovaRoute
  '/_authenticated/tutores/$id': typeof AuthenticatedTutoresIdRoute
  '/_authenticated/tutores/novo': typeof AuthenticatedTutoresNovoRoute
  '/_authenticated/alunos/': typeof AuthenticatedAlunosIndexRoute
  '/_authenticated/turmas/': typeof AuthenticatedTurmasIndexRoute
  '/_authenticated/tutores/': typeof AuthenticatedTutoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/aprovacoes'
    | '/dashboard'
    | '/meu-perfil'
    | '/alunos/$id'
    | '/alunos/novo'
    | '/turmas/$id'
    | '/turmas/nova'
    | '/tutores/$id'
    | '/tutores/novo'
    | '/alunos/'
    | '/turmas/'
    | '/tutores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/aprovacoes'
    | '/dashboard'
    | '/meu-perfil'
    | '/alunos/$id'
    | '/alunos/novo'
    | '/turmas/$id'
    | '/turmas/nova'
    | '/tutores/$id'
    | '/tutores/novo'
    | '/alunos'
    | '/turmas'
    | '/tutores'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/_authenticated/aprovacoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/meu-perfil'
    | '/_authenticated/alunos/$id'
    | '/_authenticated/alunos/novo'
    | '/_authenticated/turmas/$id'
    | '/_authenticated/turmas/nova'
    | '/_authenticated/tutores/$id'
    | '/_authenticated/tutores/novo'
    | '/_authenticated/alunos/'
    | '/_authenticated/turmas/'
    | '/_authenticated/tutores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meu-perfil': {
      id: '/_authenticated/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/meu-perfil'
      preLoaderRoute: typeof AuthenticatedMeuPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aprovacoes': {
      id: '/_authenticated/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AuthenticatedAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tutores/': {
      id: '/_authenticated/tutores/'
      path: '/tutores'
      fullPath: '/tutores/'
      preLoaderRoute: typeof AuthenticatedTutoresIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/turmas/': {
      id: '/_authenticated/turmas/'
      path: '/turmas'
      fullPath: '/turmas/'
      preLoaderRoute: typeof AuthenticatedTurmasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alunos/': {
      id: '/_authenticated/alunos/'
      path: '/alunos'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AuthenticatedAlunosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tutores/novo': {
      id: '/_authenticated/tutores/novo'
      path: '/tutores/novo'
      fullPath: '/tutores/novo'
      preLoaderRoute: typeof AuthenticatedTutoresNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tutores/$id': {
      id: '/_authenticated/tutores/$id'
      path: '/tutores/$id'
      fullPath: '/tutores/$id'
      preLoaderRoute: typeof AuthenticatedTutoresIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/turmas/nova': {
      id: '/_authenticated/turmas/nova'
      path: '/turmas/nova'
      fullPath: '/turmas/nova'
      preLoaderRoute: typeof AuthenticatedTurmasNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/turmas/$id': {
      id: '/_authenticated/turmas/$id'
      path: '/turmas/$id'
      fullPath: '/turmas/$id'
      preLoaderRoute: typeof AuthenticatedTurmasIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alunos/novo': {
      id: '/_authenticated/alunos/novo'
      path: '/alunos/novo'
      fullPath: '/alunos/novo'
      preLoaderRoute: typeof AuthenticatedAlunosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alunos/$id': {
      id: '/_authenticated/alunos/$id'
      path: '/alunos/$id'
      fullPath: '/alunos/$id'
      preLoaderRoute: typeof AuthenticatedAlunosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAprovacoesRoute: typeof AuthenticatedAprovacoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMeuPerfilRoute: typeof AuthenticatedMeuPerfilRoute
  AuthenticatedAlunosIdRoute: typeof AuthenticatedAlunosIdRoute
  AuthenticatedAlunosNovoRoute: typeof AuthenticatedAlunosNovoRoute
  AuthenticatedTurmasIdRoute: typeof AuthenticatedTurmasIdRoute
  AuthenticatedTurmasNovaRoute: typeof AuthenticatedTurmasNovaRoute
  AuthenticatedTutoresIdRoute: typeof AuthenticatedTutoresIdRoute
  AuthenticatedTutoresNovoRoute: typeof AuthenticatedTutoresNovoRoute
  AuthenticatedAlunosIndexRoute: typeof AuthenticatedAlunosIndexRoute
  AuthenticatedTurmasIndexRoute: typeof AuthenticatedTurmasIndexRoute
  AuthenticatedTutoresIndexRoute: typeof AuthenticatedTutoresIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAprovacoesRoute: AuthenticatedAprovacoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMeuPerfilRoute: AuthenticatedMeuPerfilRoute,
  AuthenticatedAlunosIdRoute: AuthenticatedAlunosIdRoute,
  AuthenticatedAlunosNovoRoute: AuthenticatedAlunosNovoRoute,
  AuthenticatedTurmasIdRoute: AuthenticatedTurmasIdRoute,
  AuthenticatedTurmasNovaRoute: AuthenticatedTurmasNovaRoute,
  AuthenticatedTutoresIdRoute: AuthenticatedTutoresIdRoute,
  AuthenticatedTutoresNovoRoute: AuthenticatedTutoresNovoRoute,
  AuthenticatedAlunosIndexRoute: AuthenticatedAlunosIndexRoute,
  AuthenticatedTurmasIndexRoute: AuthenticatedTurmasIndexRoute,
  AuthenticatedTutoresIndexRoute: AuthenticatedTutoresIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
